### ISSUE TITLE
Had to hack __init__.py to get it to load

### ISSUE THREAD

**Issue by aufflick** [tlatsas/jinja2-highlight#2]
I'm a bit of a Python noob, so I might be missing something obvious, but inside pyenv I installed jinja2-highlight via pip (as I have installed other modules fine including jinja2 itself) and got the following error on import jinja2_highlight:

```
Traceback (most recent call last):
  File "./gen_website.py", line 35, in <module>
    import jinja2_highlight
  File "/usr/local/opt/pyenv/versions/3.3.2/lib/python3.3/site-packages/jinja2_highlight/__init__.py", line 2, in <module>
    from highlight import HighlightExtension
ImportError: No module named 'highlight'
```

I fixed it by hacking jinja2_highlight/**init**.py like so:

```
import sys
import os

sys.path.append(os.path.dirname(__file__))

from highlight import HighlightExtension
```

**Comment by tlatsas** [comment]
Thanks for reporting this. Indeed this fails for me too in a clean virtualenv with python 3 (python 2.x works fine). I added a new issue to add support for python 3.
